# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
#      - image: selenium/node-chrome:3.141.59-mercury

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/testApp

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - testApp-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - testApp-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: testApp-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn package
#      - run: echo "A first hello"